import { ProductTypeEntity } from "app/ui/cardProduct";
import { CustomerEntity, StateListEntity } from "app/ui/customerDefinition";

export class Card {
    Id: number;
    CustomerId: number;
    CompanyId: number;
    CustomerNumber: string;
    CustomerName: string;
    IdentityNumber: string;
    CellPhoneNumber: string;
    Email: string;
    SearchStartDate: any;
    SearchEndDate: any;
    ZipCode: string;
    Address: string;
    BirthOfPlace: string;
    IdentityTypeId: number;
    Surname: string;
    MiddleName: string;
    Name: string;
    CompanyName: string;
    InternationalPhoneCode: string;
    CustomerTypeId: number;
    BirthDate: Date;
    CountryId: number;
    CityId: number;
    CountyId: number;
    Description: string;
    CurrencyCode: string;
    SuffixCode: string;
    IsMainAccount: boolean;
    CustomerFullName: string;
    CustomerStatus: string;
    CustomerSegment: string;
    FullCellPhoneNumber: string;
    InsertDateTime: any;
    UpdateDateTime: any;
    CustomerList: Array<CustomerEntity>;
    StateList: Array<StateListEntity>;
    ParameterList: Array<ProductTypeEntity>;
    CityName: string;
    CountyName: string;
    CustomerType: string;
    StateId: number;
    ParameterKey: string;
    CustomerSegmentId: number;
    CustomerStatusId: number;
    CustomerStatusChangeDatetime: any;
    OccupationId: number;
    AccountStatusId: number;
    AccountStatusName: string;
    AccountCode: string;
    CurrencyCodeId: number;
    CurrencyCodeName: string;
    Balance: number;
    CurrencyId: number;
    CurrencyName: string;
    HasState: boolean;
    ProductId: number;
    EmbossName: string;
    LimitResetPeriodId: number;
    LimitAmount: number;
    UsageBeginDateTime: any;
    CardStatusTypes: string;
    UsageEndDateTime: any;
    CardId: number;
    CardTokenNumber: string;
    ClearCardNumber: string;
    ExpiryDateMMYY: any;
    Cvv2: string;
    LimitCurrencyId: any;
    CardBrand: string;
    CardHolderName: string;
    ProductName: string;
    CardStatus: string;
    CardStatusId: number;
    IsActivated: boolean;
    ActivationDateTime: any;
    HasInternationalUsage: boolean;
    HasECommerceUsage: boolean;
    HasMotoUsage: boolean;
    LimitUsageAmount: number;
    LastLimitUsageDateTime: any;
    OtpSendTypeId: number;
    Cvv2RetryCount: number;
    Cvv2RetryDateTime: any;
    LastTransactionMerchant: string;
    LastTransactionAmount: number;
    LastTransactionCurrencyCode: string;
    CardStatusChangeDate: any;
    LastTransactionResponseCode: string;
    LastTransactionErrorCode: string;
    ProductBrand: string;
    ExpiryMonth: string;
    ExpiryYear: string;
    images: {
        default: boolean;
        id: string;
        url: string;
        type: string;
    }[];

    /**
     * Constructor
     *
     * @param cards
     */
    constructor(cards?) {
        cards = cards || {};
        this.Id = cards.Id;
        this.CustomerId = cards.CustomerId;
        this.CompanyId = cards.CompanyId;
        this.CustomerNumber = cards.CustomerNumber;
        this.CustomerName = cards.CustomerName;
        this.IdentityNumber = cards.IdentityNumber;
        this.CellPhoneNumber = cards.CellPhoneNumber;
        this.Email = cards.Email;
        this.SearchStartDate = cards.SearchStartDate;
        this.SearchEndDate = cards.SearchEndDate;
        this.ZipCode = cards.ZipCode;
        this.Address = cards.Address;
        this.BirthOfPlace = cards.BirthOfPlace;
        this.Surname = cards.Surname;
        this.MiddleName = cards.MiddleName;
        this.Name = cards.Name;
        this.CompanyName = cards.CompanyName;
        this.InternationalPhoneCode = cards.InternationalPhoneCode;
        this.BirthDate = cards.BirthDate;
        this.CountryId = cards.CountryId;
        this.CityId = cards.CityId;
        this.CountyId = cards.CountyId;
        this.Description = cards.Description;
        this.CurrencyCode = cards.CurrencyCode;
        this.SuffixCode = cards.SuffixCode;
        this.IsMainAccount = cards.IsMainAccount;
        this.CustomerFullName = cards.CustomerFullName;
        this.CustomerStatus = cards.CustomerStatus;
        this.CustomerSegment = cards.CustomerSegment;
        this.FullCellPhoneNumber = cards.FullCellPhoneNumber;
        this.InsertDateTime = cards.InsertDateTime;
        this.UpdateDateTime = cards.UpdateDateTime;
        this.CustomerList = cards.CustomerList;
        this.CityName = cards.CityName;
        this.CountyName = cards.CountyName;
        this.CustomerTypeId = cards.CustomerTypeId;
        this.IdentityTypeId = cards.IdentityTypeId;
        this.CustomerType = cards.CustomerType;
        this.StateId = cards.StateId;
        this.StateList = cards.StateList;
        this.ParameterKey = cards.ParameterKey;
        this.CustomerSegmentId = cards.CustomerSegmentId;
        this.CustomerStatusId = cards.CustomerStatusId;
        this.CustomerStatusChangeDatetime = cards.CustomerStatusChangeDatetime;
        this.OccupationId = cards.OccupationId;
        this.AccountStatusId = cards.AccountStatusId;
        this.AccountStatusName = cards.AccountStatusName;
        this.AccountCode = cards.AccountCode;
        this.CurrencyCodeId = cards.CurrencyCodeId;
        this.CurrencyCodeName = cards.CurrencyCodeName;
        this.Balance = cards.Balance;
        this.CurrencyId = cards.CurrencyId;
        this.CurrencyName = cards.CurrencyName;
        this.HasState = cards.HasState;
        this.ProductId = cards.ProductId;
        this.EmbossName = cards.EmbossName;
        this.LimitResetPeriodId = cards.LimitResetPeriodId;
        this.LimitAmount = cards.LimitAmount;
        this.UsageBeginDateTime = cards.UsageBeginDateTime;
        this.UsageEndDateTime = cards.UsageEndDateTime;
        this.CardId = cards.CardId;
        this.CardTokenNumber = cards.CardTokenNumber;
        this.ClearCardNumber = cards.ClearCardNumber;
        this.ExpiryDateMMYY = cards.ExpiryDateMMYY;
        this.Cvv2 = cards.Cvv2;
        this.LimitCurrencyId = cards.LimitCurrencyId;
        this.CardBrand = cards.CardBrand;
        this.CardHolderName = cards.CardHolderName;
        this.ProductName = cards.ProductName;
        this.CardStatus = cards.CardStatus;
        this.CardStatusId = cards.CardStatusId;
        this.IsActivated = cards.IsActivated;
        this.ActivationDateTime = cards.ActivationDateTime;
        this.HasInternationalUsage = cards.HasInternationalUsage;
        this.HasECommerceUsage = cards.HasECommerceUsage;
        this.HasMotoUsage = cards.HasMotoUsage;
        this.LimitUsageAmount = cards.LimitUsageAmount;
        this.LastLimitUsageDateTime = cards.LastLimitUsageDateTime;
        this.OtpSendTypeId = cards.OtpSendTypeId;
        this.Cvv2RetryCount = cards.Cvv2RetryCount;
        this.Cvv2RetryDateTime = cards.Cvv2RetryDateTime;
        this.LastTransactionMerchant = cards.LastTransactionMerchant;
        this.LastTransactionAmount = cards.LastTransactionAmount;
        this.LastTransactionCurrencyCode = cards.LastTransactionCurrencyCode;
        this.CardStatusTypes = cards.CardStatusTypes;
        this.CardStatusChangeDate = cards.CardStatusChangeDate;
        this.LastTransactionResponseCode = cards.LastTransactionResponseCode;
        this.LastTransactionErrorCode = cards.LastTransactionErrorCode;
        this.ProductBrand = cards.ProductBrand;
        this.ExpiryMonth = cards.ExpiryMonth;
        this.ExpiryYear = cards.ExpiryYear;
        this.images = cards.images || [];
    }
}
