import {
    CardEmvTransactionEntity,
    SwitchMessagesEntity,
} from "app/ui/cardTransaction";

export class CardTransaction {
    Id: number;
    CardId: number;
    CustomerId: number;
    CardTokenNumber: string;
    CompanyId: number;
    CardFinancialId: number;
    AccountId: number;
    ReferenceNumber: string;
    CardTypeId: number;
    CardBrandId: number;
    TransactionCodeId: number;
    TransactionEffectId: number;
    ResponseCode: string;
    ErrorCode: string;
    ApplicationId: number;
    SessionId: number;
    ApplicationNetwork: string;
    ProvisionTransactionType: string;
    Mti: number;
    Atc: number;
    ServerName: string;
    EmvTransactionId: number;
    SearchStartDate: any;
    SearchEndDate: any;
    CommissionAmount: number;
    SettlementStatus: string;
    TransactionEntryType: string;
    InsertDate: number;
    ProcessingCode: string;
    InsertDateTime: any;
    OriginalReferenceNumber: string;
    ErrorDescription: string;
    BillingCurrencyCode: string;
    FeeCurrencyCode: string;
    F49: string;
    F51: string;
    TenantId: number;
    TenantName: string;
    ReversalType: string;
    SessionName: string;
    TxnDescription: string;
    ProcessingGroupCode: string;
    SwitchMessages: Array<SwitchMessagesEntity>;
    EmvTransaction: CardEmvTransactionEntity;
    AcquirerId: string;
    F7: string;
    F9: string;
    F10: string;
    F11: string;
    F12: string;
    F13: string;
    F14: string;
    Mcc: string;
    F22: string;
    CardSequenceNumber: string;

    F25: string;
    F26: string;
    F28: string;
    F32: string;
    F33: string;
    F37: string;
    F38: string;
    F41: string;
    F42: string;
    F43Name: string;
    F43City: string;
    F43State: string;
    F43Country: string;
    F44: string;
    F48: string;
    F53: string;
    F60: string;
    F61: string;
    F62: string;
    F63: string;
    F90: string;
    F95: string;
    F54: string;
    CvmResult: string;
    CvvCheckResult: string;
    Cvv2CheckResult: string;
    CavvIndicator: string;
    CavvCheckResult: string;
    OnlinePinCheckResult: string;
    OfflinePinCheckResult: string;
    EmvCheckResult: string;
    ClearingMatchStatus: string;
    EndPointAddress: string;
    TransactionCategoryCode: string;
    TerminalType: string;
    CardTransactionSource: string;
    SwitchSettlementDate: string;
    PosCountryCode: string;
    TransactionIdentifier: string;
    IsExternalAuthorizedTransaction: boolean;
    IsFinancialTransaction: boolean;
    IsSucceded: boolean;
    IsReversed: boolean;
    IsOnusTransaction: boolean;
    IsSystemTransaction: boolean;
    HasCvv: boolean;
    HasCvv2: boolean;
    HasCavv: boolean;
    HasOnlinePin: boolean;
    HasOfflinePin: boolean;
    HasEmvData: boolean;
    HasPartialReversal: boolean;
    HasIncrementalAuthorization: boolean;
    HasSwitchSettlementDate: boolean;
    HasAccountUsage: boolean;
    ExternalAuthorizationProfileId: number;
    AvailableBalance: number;
    BillingAmount: number;
    FeeAmount: number;
    F4: number;
    F6: number;
    ClearingTransactionId: number;
    CurrencyRate: number;
    IncrmentalAuthorizationCount: number;
    OriginalF4: number;
    OriginalF6: number;
    OriginalBillingAmount: number;
    TransactionDateTime: any;
    ReversedDateTime: any;
    SettlementDate: any;
    TransactionLocalDateTime: any;
    ServerDateTime: any;
    LastIncrementalAuthorizationDateTime: any;
    F55Length: number;
    F55Tag5F34: string;
    F55Tag5F2A: string;
    F55Tag82: string;
    F55Tag84: string;
    F55Tag95: string;
    F55Tag9A: string;
    F55Tag9C: string;
    F55Tag9F02: string;
    F55Tag9F03: string;
    F55Tag9F10: string;
    F55Tag9F1A: string;
    F55Tag9F26: string;
    F55Tag9F27: string;
    F55Tag9F33: string;
    F55Tag9F34: string;
    F55Tag9F36: string;
    F55Tag9F37: string;
    F55Tag91: string;
    F55Tag71: string;
    F55Tag72: string;
    ApplicationType: string;
    TransactionType: string;
    MerchantCode: string;
    TerminalId: string;
    TraceNumber: string;
    Rrn: string;
    TransactionAmount: number;
    RemoteIpAddress: string;
    RemotePort: number;
    LocalIpAddress: string;
    LocalPort: number;
    RoutedRemoteIpAddress: string;
    RoutedRemotePort: number;
    RoutedLocalIpAddress: string;
    RoutedLocalPort: number;
    HexMessage: string;
    TransactionCurrencyCode: string;
    AuthorizationCode: string;
    SettlementAmount: number;
    SettlementCurrencyCode: string;
    SearchStartTime: any;
    SearchEndTime: any;
    AuthorizationIsSucceded: boolean;
    AuthorizationResponseCode: string;
    AuthorizationErrorCode: string;
    AuthorizationErrorDescription: string;
    TotalElapsed: number;
    TotalAuthorizationElapsed: number;
    images: {
        default: boolean;
        id: string;
        url: string;
        type: string;
    }[];

    /**
     * Constructor
     *
     * @param cardTransaction
     */
    constructor(cardTransaction?) {
        cardTransaction = cardTransaction || {};
        this.Id = cardTransaction.Id;
        this.TenantName = cardTransaction.TenantName;
        this.TenantId = cardTransaction.TenantId;
        this.CardId = cardTransaction.CardId;
        this.AuthorizationIsSucceded = cardTransaction.AuthorizationIsSucceded;
        this.AuthorizationResponseCode =
            cardTransaction.AuthorizationResponseCode;
        this.AuthorizationErrorCode = cardTransaction.AuthorizationErrorCode;
        this.AuthorizationErrorDescription =
            cardTransaction.AuthorizationErrorDescription;
        this.CustomerId = cardTransaction.CustomerId;
        this.TotalAuthorizationElapsed =
            cardTransaction.TotalAuthorizationElapsed;
        this.TotalElapsed = cardTransaction.TotalElapsed;
        this.CardTokenNumber = cardTransaction.CardTokenNumber;
        this.CompanyId = cardTransaction.CompanyId;
        this.CardFinancialId = cardTransaction.CardFinancialId;
        this.AccountId = cardTransaction.AccountId;
        this.ReferenceNumber = cardTransaction.ReferenceNumber;
        this.CardTypeId = cardTransaction.CardTypeId;
        this.CardBrandId = cardTransaction.CardBrandId;
        this.TransactionCodeId = cardTransaction.TransactionCodeId;
        this.TransactionEffectId = cardTransaction.TransactionEffectId;
        this.ResponseCode = cardTransaction.ResponseCode;
        this.ErrorCode = cardTransaction.ErrorCode;
        this.ApplicationId = cardTransaction.ApplicationId;
        this.SessionId = cardTransaction.SessionId;
        this.ApplicationNetwork = cardTransaction.ApplicationNetwork;
        this.ProvisionTransactionType =
            cardTransaction.ProvisionTransactionType;
        this.Mti = cardTransaction.Mti;
        this.Atc = cardTransaction.Atc;
        this.ServerName = cardTransaction.ServerName;
        this.EmvTransactionId = cardTransaction.EmvTransactionId;
        this.SearchStartDate = cardTransaction.SearchStartDate;
        this.SearchEndDate = cardTransaction.SearchEndDate;
        this.CommissionAmount = cardTransaction.CommissionAmount;
        this.SettlementStatus = cardTransaction.SettlementStatus;
        this.TransactionEntryType = cardTransaction.TransactionEntryType;
        this.ProcessingCode = cardTransaction.ProcessingCode;
        this.InsertDateTime = cardTransaction.InsertDateTime;
        this.OriginalReferenceNumber = cardTransaction.OriginalReferenceNumber;
        this.ErrorDescription = cardTransaction.ErrorDescription;
        this.BillingCurrencyCode = cardTransaction.BillingCurrencyCode;
        this.FeeCurrencyCode = cardTransaction.FeeCurrencyCode;
        this.F49 = cardTransaction.F49;
        this.F51 = cardTransaction.F51;
        this.ReversalType = cardTransaction.ReversalType;
        this.TxnDescription = cardTransaction.TxnDescription;
        this.ProcessingGroupCode = cardTransaction.ProcessingGroupCode;
        this.AcquirerId = cardTransaction.AcquirerId;
        this.CvmResult = cardTransaction.CvmResult;
        this.CvvCheckResult = cardTransaction.CvvCheckResult;
        this.Cvv2CheckResult = cardTransaction.Cvv2CheckResult;
        this.CavvIndicator = cardTransaction.CavvIndicator;
        this.CavvCheckResult = cardTransaction.CavvCheckResult;
        this.OnlinePinCheckResult = cardTransaction.OnlinePinCheckResult;
        this.OfflinePinCheckResult = cardTransaction.OfflinePinCheckResult;
        this.EmvCheckResult = cardTransaction.EmvCheckResult;
        this.ClearingMatchStatus = cardTransaction.ClearingMatchStatus;
        this.EndPointAddress = cardTransaction.EndPointAddress;
        this.TransactionCategoryCode = cardTransaction.TransactionCategoryCode;
        this.TerminalType = cardTransaction.TerminalType;
        this.CardTransactionSource = cardTransaction.CardTransactionSource;
        this.SwitchSettlementDate = cardTransaction.SwitchSettlementDate;
        this.PosCountryCode = cardTransaction.PosCountryCode;
        this.TransactionIdentifier = cardTransaction.TransactionIdentifier;
        this.IsExternalAuthorizedTransaction =
            cardTransaction.IsExternalAuthorizedTransaction;
        this.IsFinancialTransaction = cardTransaction.IsFinancialTransaction;
        this.IsSucceded = cardTransaction.IsSucceded;
        this.IsReversed = cardTransaction.IsReversed;
        this.IsOnusTransaction = cardTransaction.IsOnusTransaction;
        this.IsSystemTransaction = cardTransaction.IsSystemTransaction;
        this.HasCvv = cardTransaction.HasCvv;
        this.HasCvv2 = cardTransaction.HasCvv2;
        this.HasCavv = cardTransaction.HasCavv;
        this.HasOnlinePin = cardTransaction.HasOnlinePin;
        this.HasOfflinePin = cardTransaction.HasOfflinePin;
        this.HasEmvData = cardTransaction.HasEmvData;
        this.HasPartialReversal = cardTransaction.HasPartialReversal;
        this.HasIncrementalAuthorization =
            cardTransaction.HasIncrementalAuthorization;
        this.HasSwitchSettlementDate = cardTransaction.HasSwitchSettlementDate;
        this.HasAccountUsage = cardTransaction.HasAccountUsage;
        this.ExternalAuthorizationProfileId =
            cardTransaction.ExternalAuthorizationProfileId;
        this.AvailableBalance = cardTransaction.AvailableBalance;
        this.BillingAmount = cardTransaction.BillingAmount;
        this.FeeAmount = cardTransaction.FeeAmount;
        this.F4 = cardTransaction.F4;
        this.F6 = cardTransaction.F6;
        this.ClearingTransactionId = cardTransaction.ClearingTransactionId;
        this.CurrencyRate = cardTransaction.CurrencyRate;
        this.IncrmentalAuthorizationCount =
            cardTransaction.IncrmentalAuthorizationCount;
        this.OriginalF4 = cardTransaction.OriginalF4;
        this.OriginalF6 = cardTransaction.OriginalF6;
        this.OriginalBillingAmount = cardTransaction.OriginalBillingAmount;
        this.TransactionDateTime = cardTransaction.TransactionDateTime;
        this.ReversedDateTime = cardTransaction.ReversedDateTime;
        this.SettlementDate = cardTransaction.SettlementDate;
        this.TransactionLocalDateTime =
            cardTransaction.TransactionLocalDateTime;
        this.ServerDateTime = cardTransaction.ServerDateTime;
        this.LastIncrementalAuthorizationDateTime =
            cardTransaction.LastIncrementalAuthorizationDateTime;
        this.F55Length = cardTransaction.F55Length;
        this.F55Tag5F34 = cardTransaction.F55Tag5F34;
        this.F55Tag5F2A = cardTransaction.F55Tag5F2A;
        this.F55Tag82 = cardTransaction.F55Tag82;
        this.F55Tag84 = cardTransaction.F55Tag84;
        this.F55Tag95 = cardTransaction.F55Tag95;
        this.F55Tag9A = cardTransaction.F55Tag9A;
        this.SessionName = cardTransaction.SessionName;
        this.F55Tag9C = cardTransaction.F55Tag9C;
        this.F55Tag9F02 = cardTransaction.F55Tag9F02;
        this.F55Tag9F03 = cardTransaction.F55Tag9F03;
        this.F55Tag9F10 = cardTransaction.F55Tag9F10;
        this.F55Tag9F1A = cardTransaction.F55Tag9F1A;
        this.F55Tag9F26 = cardTransaction.F55Tag9F26;
        this.F55Tag9F27 = cardTransaction.F55Tag9F27;
        this.F55Tag9F33 = cardTransaction.F55Tag9F33;
        this.F55Tag9F34 = cardTransaction.F55Tag9F34;
        this.F7 = cardTransaction.F7;
        this.F9 = cardTransaction.F9;
        this.F10 = cardTransaction.F10;
        this.F11 = cardTransaction.F11;
        this.F12 = cardTransaction.F12;
        this.F13 = cardTransaction.F13;
        this.F14 = cardTransaction.F14;
        this.Mcc = cardTransaction.Mcc;
        this.F22 = cardTransaction.F22;
        this.CardSequenceNumber = cardTransaction.CardSequenceNumber;
        this.F25 = cardTransaction.F25;
        this.F26 = cardTransaction.F26;
        this.F28 = cardTransaction.F28;
        this.F32 = cardTransaction.F32;
        this.F33 = cardTransaction.F33;
        this.F37 = cardTransaction.F37;
        this.F38 = cardTransaction.F38;
        this.F41 = cardTransaction.F41;
        this.F42 = cardTransaction.F42;
        this.F43City = cardTransaction.F43City;
        this.F43State = cardTransaction.F43State;
        this.F43Country = cardTransaction.F43Country;
        this.F44 = cardTransaction.F44;
        this.F48 = cardTransaction.F48;
        this.F53 = cardTransaction.F53;
        this.F60 = cardTransaction.F60;
        this.F61 = cardTransaction.F61;
        this.F62 = cardTransaction.F62;
        this.F63 = cardTransaction.F63;
        this.F90 = cardTransaction.F90;
        this.F95 = cardTransaction.F95;
        this.F54 = cardTransaction.F54;
        this.F55Tag9F36 = cardTransaction.F55Tag9F36;
        this.F55Tag9F37 = cardTransaction.F55Tag9F37;
        this.F55Tag91 = cardTransaction.F55Tag91;
        this.F55Tag71 = cardTransaction.F55Tag71;
        this.F55Tag72 = cardTransaction.F55Tag72;
        this.ApplicationType = cardTransaction.ApplicationType;
        this.TransactionType = cardTransaction.TransactionType;
        this.MerchantCode = cardTransaction.MerchantCode;
        this.TerminalId = cardTransaction.TerminalId;
        this.TraceNumber = cardTransaction.TraceNumber;
        this.TransactionAmount = cardTransaction.TransactionAmount;
        this.RemoteIpAddress = cardTransaction.RemoteIpAddress;
        this.RemotePort = cardTransaction.RemotePort;
        this.LocalIpAddress = cardTransaction.LocalIpAddress;
        this.LocalPort = cardTransaction.LocalPort;
        this.RoutedRemoteIpAddress = cardTransaction.RoutedRemoteIpAddress;
        this.RoutedRemotePort = cardTransaction.RoutedRemotePort;
        this.RoutedLocalIpAddress = cardTransaction.RoutedLocalIpAddress;
        this.RoutedLocalPort = cardTransaction.RoutedLocalPort;
        this.HexMessage = cardTransaction.HexMessage;
        this.TransactionCurrencyCode = cardTransaction.TransactionCurrencyCode;
        this.AuthorizationCode = cardTransaction.AuthorizationCode;
        this.SettlementAmount = cardTransaction.SettlementAmount;
        this.SettlementCurrencyCode = cardTransaction.SettlementCurrencyCode;
        this.SearchStartTime = cardTransaction.SearchStartTime;
        this.SearchEndTime = cardTransaction.SearchEndTime;
        this.InsertDate = cardTransaction.InsertDate;
        this.EmvTransaction = cardTransaction.EmvTransaction;
        this.SwitchMessages = cardTransaction.SwitchMessages;
        this.images = cardTransaction.images || [];
    }
}
